name: Integration Tests
on:
  # Run this on pushes to main
  push:
    branches:
    - main

  # And when PRs operations are done
  pull_request:
    types:
    - opened
    - reopened
    - synchronize

  # And once daily at 12 AM UTC, 8 PM EST
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set VERSION
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build plugin (statically)
      run: |
        CGO_ENABLED=0 go build -tags netgo -ldflags '-extldflags "-static"' \
        -o $PWD/dist/terraform-provider-conjur_linux_amd64/terraform-provider-conjur_v${VERSION} .

    - name: Run Tests
      run: |
        ./bin/test oss
